# Homelab InfluxDB config
adminUser:
  organization: "homelab"
  bucket: "mqtt"
  user: "admin"
  existingSecret: homelab-influxdb-credentials

persistence:
  enabled: true
  storageClass: nfs-rwx
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
