# Homelab InfluxDB config
adminUser:
  organization: "homelab"
  bucket: "mqtt"
  user: "admin"
  existingSecret: homelab-influxdb-credentials

persistence:
  enabled: true
  storageClass: nfs-rwx
  size: 5Gi

# Security context for NFS
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Disable setPermissions init container
setPermissions:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
