---
# Istio CNI - homelab values

cni:
  # k3s/k3d specific paths
  cniBinDir: /bin
  cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
