---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: homelab
            cluster: https://kubernetes.default.svc
            namespace: monitoring
            helmRevision: "72.*"
            env: homelab
            region: local
            type: homelab
  template:
    metadata:
      name: kube-prometheus-stack-{{ .name }}
      labels:
        app.kubernetes.io/name: kube-prometheus-stack
        app.kubernetes.io/instance: kube-prometheus-stack-{{ .name }}
        env: "{{ .env }}"
        cluster: "{{ .name }}"
        region: "{{ .region }}"
        type: "{{ .type }}"
      annotations:
        argocd.argoproj.io/sync-wave: "4"
        homelab.argocd.io/cluster-url: "{{ .cluster }}"
    spec:
      project: platform-observability
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: "{{ .helmRevision }}"
          helm:
            releaseName: kube-prometheus-stack
            valueFiles:
              - $values/values/kube-prometheus-stack/common/values.yaml
              - $values/values/kube-prometheus-stack/{{ .region }}/{{ .env }}/values.yaml
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          ref: values
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          path: extras/{{ .region }}/kube-prometheus-stack
      destination:
        server: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      revisionHistoryLimit: 5
      info:
        - name: Region
          value: "{{ .region }}"
        - name: Environment
          value: "{{ .env }}"
        - name: Type
          value: "{{ .type }}"
        - name: Chart Version
          value: "{{ .helmRevision }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
        managedNamespaceMetadata:
          labels:
            owner: argocd
            app.kubernetes.io/part-of: monitoring
            region: "{{ .region }}"
            env: "{{ .env }}"
            istio.io/dataplane-mode: ambient
          annotations:
            argocd.argoproj.io/managed-by: "kube-prometheus-stack-{{ .name }}"
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
