# Cloudflared homelab configuration

cloudflare:
  account: "588987ca16ff5dc7e60391ce0c9a9f38"
  tunnelName: "macbook-air"
  tunnelId: "9f0067e6-dfcb-4bc1-a12f-751763b7a14a"
  # Secret from ExternalSecret
  secretName: cloudflared-tunnel-credentials

  ingress:
    - hostname: grafana.devopslaboratory.org
      service: http://envoy-cloudflared-cloudflare-gateway.cloudflared.svc.cluster.local:80
    - service: http_status:404
