---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: emqx
  namespace: monitoring
  labels:
    app: emqx
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - emqx
  selector:
    matchLabels:
      apps.emqx.io/instance: emqx
      apps.emqx.io/managed-by: emqx-operator
  endpoints:
    - port: dashboard
      path: /api/v5/prometheus/stats
      interval: 30s
      scrapeTimeout: 10s
